<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.esternit</groupId>
    <artifactId>telegram-spring-boot-parent</artifactId>
    <version>0.1.1</version>
    <packaging>pom</packaging>

    <name>Telegram Spring Boot Parent</name>
    <description>Parent POM for Telegram Spring Boot Starter and its tests</description>
    <url>https://github.com/Esternit/telegram-spring-boot</url>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <spring-boot.version>3.5.4</spring-boot.version>
        <spring-framework.version>6.2.8</spring-framework.version>
        <spring-aop.version>6.2.9</spring-aop.version>
        <aspectj.version>1.9.24</aspectj.version>
        <slf4j.version>2.0.9</slf4j.version>
        <lombok.version>1.18.30</lombok.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>telegram-spring-boot-starter</module>
        <module>telegram-spring-tests</module>
    </modules>
</project>